### Project specific config ###
language: generic

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable

    - os: linux
      env: ATOM_CHANNEL=beta

    - os: osx
      env: ATOM_CHANNEL=stable

env:
  global:
    # Pre-install the required language file as package activation doesn't wait
    # for the installation to complete.
    - APM_TEST_PACKAGES="language-review language-asciidoc"

### Generic setup follows ###
install:
  - export CXX=g++-4.8
  - npm install

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - g++-4.8
